<?php
/**
 * @package      VirtualCurrency
 * @subpackage   Components
 * @author       Todor Iliev
 * @copyright    Copyright (C) 2016 Todor Iliev <todor@itprism.com>. All rights reserved.
 * @license      GNU General Public License version 3 or later; see LICENSE.txt
 */

// no direct access
defined('_JEXEC') or die;

class VirtualCurrencyModelImport extends JModelForm
{

    /**
     * Method to get the record form.
     *
     * @param   array   $data     An optional array of data for the form to interogate.
     * @param   boolean $loadData True if the form is to load its own data (default case), false if not.
     *
     * @return  JForm   A JForm object on success, false on failure
     * @since   1.6
     */
    public function getForm($data = array(), $loadData = true)
    {
        // Get the form.
        $form = $this->loadForm($this->option . '.import', 'import', array('control' => 'jform', 'load_data' => $loadData));
        if (empty($form)) {
            return false;
        }

        return $form;
    }

    /**
     * Method to get the data that should be injected in the form.
     *
     * @return  mixed   The data for the form.
     * @since   1.6
     */
    protected function loadFormData()
    {
        // Check the session for previously entered form data.
        $data = JFactory::getApplication()->getUserState($this->option . '.edit.import.data', array());

        return $data;
    }

    public function uploadFile($fileData, $type)
    {
        $app = JFactory::getApplication();
        /** @var $app JApplicationAdministrator */

        jimport('joomla.filesystem.archive');

        $uploadedFile = JArrayHelper::getValue($fileData, 'tmp_name');
        $uploadedName = JArrayHelper::getValue($fileData, 'name');
        $errorCode    = JArrayHelper::getValue($fileData, 'error');

        $source = JPath::clean($app->get('tmp_path') . DIRECTORY_SEPARATOR . JFile::makeSafe($uploadedName));

        $file = new Prism\File\File();

        // Prepare size validator.
        $KB       = 1024 * 1024;
        $fileSize = (int)$app->input->server->get('CONTENT_LENGTH');

        $mediaParams   = JComponentHelper::getParams('com_media');
        /** @var $mediaParams Joomla\Registry\Registry */

        $uploadMaxSize = $mediaParams->get('upload_maxsize') * $KB;

        // Prepare size validator.
        $sizeValidator = new Prism\File\Validator\Size($fileSize, $uploadMaxSize);

        // Prepare server validator.
        $serverValidator = new Prism\File\Validator\Server($errorCode, array(UPLOAD_ERR_NO_FILE));

        $file->addValidator($sizeValidator);
        $file->addValidator($serverValidator);

        // Validate the file
        if (!$file->isValid()) {
            throw new RuntimeException($file->getError());
        }

        // Prepare uploader object.
        $uploader = new Prism\File\Uploader\Local($uploadedFile);
        $uploader->setDestination($source);

        // Upload the file
        $file->setUploader($uploader);
        $file->upload();

        $fileName = basename($source);

        // Extract file if it is archive
        $ext = JString::strtolower(JFile::getExt($fileName));
        if (strcmp($ext, 'zip') === 0) {

            $destFolder = JPath::clean($app->get('tmp_path') . DIRECTORY_SEPARATOR . $type);
            if (is_dir($destFolder)) {
                JFolder::delete($destFolder);
            }

            $filePath = $this->extractFile($source, $destFolder);

        } else {
            $filePath = $source;
        }

        return $filePath;
    }

    public function extractFile($file, $destFolder)
    {
        $filePath = null;

        // extract type
        $zipAdapter = JArchive::getAdapter('zip');
        $zipAdapter->extract($file, $destFolder);

        $dir = new DirectoryIterator($destFolder);

        $fileName = JFile::stripExt(basename($file));

        foreach ($dir as $fileinfo) {

            $currentFileName = JFile::stripExt($fileinfo->getFilename());

            if (!$fileinfo->isDot() and strcmp($fileName, $currentFileName) === 0) {
                $filePath = JPath::clean($destFolder . DIRECTORY_SEPARATOR . JFile::makeSafe($fileinfo->getFilename()));
                break;
            }

        }

        return $filePath;
    }
    
    /**
     *
     * Import currencies from XML file.
     * The XML file is generated by the current extension ( Challenges )
     *
     * @param string $file    A path to file
     * @param bool   $resetId Reset existing IDs with new ones.
     */
    public function importCurrencies($file, $resetId = false)
    {
        $xmlstr  = file_get_contents($file);
        $content = new SimpleXMLElement($xmlstr);

        if ($content !== null) {

            // Check for existed currencies.
            $db    = $this->getDbo();
            $query = $db->getQuery(true);
            $query
                ->select('COUNT(*)')
                ->from($db->quoteName('#__vc_realcurrencies', 'a'));

            $db->setQuery($query);
            $result = $db->loadResult();

            if ($result !== null and (int)$result > 0) { // Update current currencies and insert newest.
                $this->updateCurrencies($content);
            } else { // Insert new ones
                $this->insertCurrencies($content, $resetId);
            }
        }
    }

    protected function insertCurrencies($content, $resetId)
    {
        $items = array();

        $db = $this->getDbo();

        // Generate data for importing.
        foreach ($content as $item) {

            $title = JString::trim($item->title);
            $code  = JString::trim($item->code);
            if (!$title or !$code) {
                continue;
            }

            $id = (!$resetId) ? (int)$item->id : 'null';

            $items[] = $id . ',' . $db->quote($title) . ',' . $db->quote($code) . ',' . $db->quote(JString::trim($item->symbol)) . ',' . (int)$item->position;
        }

        $query = $db->getQuery(true);

        $columns = array('id', 'title', 'code', 'symbol', 'position');

        $query
            ->insert($db->quoteName('#__vc_realcurrencies'))
            ->columns($db->quoteName($columns))
            ->values($items);

        $db->setQuery($query);
        $db->execute();
    }

    /**
     * Update the currencies with new columns.
     *
     * @param SimpleXMLElement $content
     */
    protected function updateCurrencies($content)
    {
        JLoader::register('VirtualcurrencyTableRealCurrency', JPATH_ADMINISTRATOR .'/components/com_virtualcurrency/tables/realcurrency.php');
        $db = $this->getDbo();

        foreach ($content as $item) {

            $code = JString::trim($item->code);

            $keys = array('code' => $code);

            $table = new VirtualcurrencyTableRealCurrency($db);
            $table->load($keys);

            if (!$table->get('id')) {
                $table->set('title', JString::trim($item->title));
                $table->set('code', $code);
                $table->set('position', 0);
            }

            // Update the symbol if missing.
            if (!$table->get('symbol') and $item->symbol !== '') {
                $table->set('symbol', JString::trim($item->symbol));
            }

            $table->store();
        }
    }

    public function removeAll()
    {
        $db = $this->getDbo();
        $db->truncateTable('#__vc_realcurrencies');
    }
}
